export { IconBooks } from './books'
export { IconComputer } from './computer'
export { IconDiagram } from './diagram'
export { IconEmptyStar } from './empty-star'
export { IconFilledStar } from './filled-star'
export { IconInfo } from './info'
export { IconProfile } from './profile'
export * from './social'
export { IconUser } from './user'
